/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;


import Modelo.Vendedor;
import Negocio.EVendedor;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;

public class FrmListadoVendedor extends javax.swing.JFrame implements IFormActive {

    /**
     * Creates new form FrmListadoRoles
     */
    DefaultTableModel defaultTable = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    public FrmListadoVendedor() {
        initComponents();

        this.setTitle("Vendedor");
        this.setLocationRelativeTo(this);

        this.defaultTable.addColumn("Id");
        this.defaultTable.addColumn("Nombres");
        this.defaultTable.addColumn("Apellidos");
        this.defaultTable.addColumn("Dni");
        this.defaultTable.addColumn("Telefono");

        this.tblVendedor.setModel(defaultTable);

        TableColumnModel columnModel = tblVendedor.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(15);
        columnModel.getColumn(1).setPreferredWidth(180);
        columnModel.getColumn(2).setPreferredWidth(50);
        columnModel.getColumn(3).setPreferredWidth(50);
        columnModel.getColumn(4).setPreferredWidth(50);
        tblVendedor.setRowHeight(50);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        columnModel.getColumn(4).setCellRenderer(centerRenderer);

        loadTable();

        Border line = BorderFactory.createLineBorder(Color.DARK_GRAY);
        Border empty = new EmptyBorder(0, 10, 0, 0);
        CompoundBorder border = new CompoundBorder(line, empty);
        txtSearch.setBorder(border);
    }

    /*@Override
    public void updateList(String name){
        System.out.println("Hola: "+name);
        //this.txtSearch.setText(name);
    }*/
    /**
     *
     */
    @Override
    public final void loadTable() {
        try {

            for (int i = this.defaultTable.getRowCount() - 1; i >= 0; i--) {
                this.defaultTable.removeRow(i);
            }

            Vendedor clsCli = new Vendedor();
            ArrayList arrayList = clsCli.getAll();

            for (int i = 0; i < arrayList.size(); i++) {
                EVendedor vendedor = (EVendedor) arrayList.get(i);
                this.defaultTable.addRow(new Object[]{});
                this.defaultTable.setValueAt(vendedor.getId(), i, 0);
                this.defaultTable.setValueAt(vendedor.getNombres(), i, 1);
                this.defaultTable.setValueAt(vendedor.getApellidos(), i, 2);
                this.defaultTable.setValueAt(vendedor.getDni(), i, 3);
                this.defaultTable.setValueAt(vendedor.getTelefono(), i, 4);
            }

            EColorTableCell foreColor = new EColorTableCell();
            foreColor.setColumnIndex(4);
            tblVendedor.getColumnModel().getColumn(4).setCellRenderer(foreColor);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), Module.titleMessage, JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVendedor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento de Roles");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnNew.setBackground(new java.awt.Color(102, 0, 102));
        btnNew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/disco-flexible.png"))); // NOI18N
        btnNew.setText("NUEVO");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        tblVendedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVendedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVendedor);
        if (tblVendedor.getColumnModel().getColumnCount() > 0) {
            tblVendedor.getColumnModel().getColumn(0).setResizable(false);
            tblVendedor.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblVendedor.getColumnModel().getColumn(1).setResizable(false);
            tblVendedor.getColumnModel().getColumn(2).setResizable(false);
            tblVendedor.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar.png"))); // NOI18N
        jLabel1.setText("BUSCAR:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(39, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch)
                        .addGap(80, 80, 80)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        try {

            String txtNombre = this.txtSearch.getText().trim();
            if (txtNombre.equals("")) {
                loadTable();
                return;
            }

            for (int i = this.defaultTable.getRowCount() - 1; i >= 0; i--) {
                this.defaultTable.removeRow(i);
            }

            Vendedor clsCli = new Vendedor();
            ArrayList arrayList = clsCli.searchByName(txtNombre);

            for (int i = 0; i < arrayList.size(); i++) {
                EVendedor vendedor = (EVendedor) arrayList.get(i);
                this.defaultTable.addRow(new Object[]{});

                this.defaultTable.setValueAt(vendedor.getId(), i, 0);
                this.defaultTable.setValueAt(vendedor.getNombres(), i, 1);
                this.defaultTable.setValueAt(vendedor.getApellidos(), i, 2);
                this.defaultTable.setValueAt(vendedor.getDni(), i, 3);
                this.defaultTable.setValueAt(vendedor.getTelefono(), i, 4);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), Module.titleMessage, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        EForm formActive = Module.formActive;
        formActive.setCaller(this);

//        EClientes cli = Module.rol;
//        cli.setId(0);
//        cli.setNombre("");
//        cli.setEstado("");
        EVendedor ven = Module.ven;
        ven.setId(0);
        ven.setNombres("");
        ven.setApellidos("");
        ven.setDni("");
        ven.setTelefono("");

        FrmVendedor formVendedor = new FrmVendedor();
        formVendedor.setVisible(true);
        formVendedor.pack();
        //formRoles.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnNewActionPerformed

    private void tblVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVendedorMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int id = (int) tblVendedor.getValueAt(tblVendedor.getSelectedRow(), 0);
            String nombres = tblVendedor.getValueAt(tblVendedor.getSelectedRow(), 1).toString();
            String apellidos = tblVendedor.getValueAt(tblVendedor.getSelectedRow(), 2).toString();
            String dni = tblVendedor.getValueAt(tblVendedor.getSelectedRow(), 3).toString();
            String telefono = tblVendedor.getValueAt(tblVendedor.getSelectedRow(), 4).toString();

            EVendedor ven = Module.ven;
            ven.setId(id);
            ven.setNombres(nombres);
            ven.setApellidos(apellidos);
            ven.setDni(apellidos);
            ven.setTelefono(telefono);

            EForm formActive = Module.formActive;
            formActive.setCaller(this);

            FrmVendedor formVendedor = new FrmVendedor();
            formVendedor.setVisible(true);
            formVendedor.pack();
        }
    }//GEN-LAST:event_tblVendedorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListadoVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListadoVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListadoVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListadoVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListadoVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblVendedor;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
